---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: heimdall-deployment
   labels:
     app: heimdall
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: heimdall
   template:
     metadata:
       labels:
         app: heimdall

     spec:
      containers:
         - name: heimdall
           image: linuxserver/heimdall
           imagePullPolicy: Always
           resources:
             limits:
               cpu: "150m"
             requests:
               cpu: "150m"
           ports:
             - containerPort: 7878
           volumeMounts:
             - mountPath: /config
               name: heimdall-volume
      
      volumes:
        - name: heimdall-volume
          persistentVolumeClaim:
           claimName: heimdall-volume-claim

---
kind: Service
apiVersion: v1
metadata:
  name: heimdall-service
spec:
  selector:
    app: heimdall
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
